# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='ItemSpec',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='itemkind',
            options={'verbose_name': 'Tipo de Item', 'verbose_name_plural': 'Tipos de Item'},
        ),
        migrations.AlterModelOptions(
            name='itemspec',
            options={'verbose_name': 'Modelo do Item', 'verbose_name_plural': 'Modelos do Item'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='model',
            new_name='spec',
        ),
    ]
