# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170807_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='intern_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Interno'),
        ),
    ]
