# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_item_intern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkind',
            name='name',
            field=models.CharField(default='tipo', max_length=100, verbose_name='Kind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='name',
            field=models.CharField(default='spec', max_length=100, verbose_name='Model'),
            preserve_default=False,
        ),
    ]
