# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cod', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cod', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Codigo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_discipline', to='college.Course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
