# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_planned_date', models.DateTimeField(verbose_name='Removal planned date')),
                ('delivery_planned_date', models.DateTimeField(verbose_name='Delivery planned date')),
                ('removal_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Removal date')),
                ('delivery_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Delivery date')),
                ('reservation', models.TextField(blank=True, null=True, verbose_name='Reservation')),
                ('terms', models.BooleanField(default=False, help_text='Designates if the user accepted the terms of use', verbose_name='Terms')),
                ('status', models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Withdrawn'), (2, 'Delivered')], default=0, verbose_name='Status')),
                ('items', models.ManyToManyField(related_name='loan_items', to='collection.Item', verbose_name='Items')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_official', to=settings.AUTH_USER_MODEL, verbose_name='Official')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_professor', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_student', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('students', models.ManyToManyField(related_name='loan_students', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
        ),
    ]
