# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
    ]
