# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_auto_20170807_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='official',
        ),
        migrations.AddField(
            model_name='loan',
            name='authorized_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Authorized date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='cancel_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancel date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='official_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_official_deliver', to=settings.AUTH_USER_MODEL, verbose_name='Official Deliver'),
        ),
        migrations.AddField(
            model_name='loan',
            name='official_withdrawn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_official_withdrawn', to=settings.AUTH_USER_MODEL, verbose_name='Official Withdrawn'),
        ),
        migrations.AddField(
            model_name='loan',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Scheduled date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Authorized'), (2, 'Withdrawn'), (3, 'Delivered'), (4, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
