# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20170808_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='external',
            field=models.BooleanField(default=False, verbose_name='External'),
        ),
    ]
