# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Empr\xe9stimo', 'verbose_name_plural': 'Empr\xe9stimos'},
        ),
    ]
