# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20170831_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='delivery_planned_date',
            field=models.DateField(verbose_name='Delivery planned date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='removal_planned_date',
            field=models.DateField(verbose_name='Removal planned date'),
        ),
    ]
