# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('loan', '0006_auto_20170906_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_discipline', to='college.Discipline', verbose_name='Disciplina'),
            preserve_default=False,
        ),
    ]
