# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Student'), (1, 'Officer'), (2, 'Professor'), (3, 'Chief')], default=0, verbose_name='Level'),
        ),
    ]
