# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_auto_20170905_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='ra',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RA'),
        ),
    ]
